version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:7777"
    container_name: music_service
    volumes:
      - .:/music_service
    ports:
      - "7777:7777"